### ISSUE TITLE
misleading terms in the README

### ISSUE THREAD

**Issue by whot** [jarnos/block-scroll-mod-x11#1]
> that has suitable xinput library

[xinput is a tool](https://gitlab.freedesktop.org/xorg/app/xinput) that uses [libXi](https://gitlab.freedesktop.org/xorg/lib/libXi) to access the X Input extension. There's no such thing as an "xinput library", and yes, I know, the terms are badly overloaded.

**Comment by jarnos** [comment]
Better now?

**Comment by whot** [comment]
yep. two nitpicks: "XInput2" (uppercase i) and english grammar requires "an XInput2 API", but neither of those chances is crucial ;)

Thanks!
